
project_id = "lvyqjogxspinjufcrmnf"

[api]
enabled = true
port = 8080
schemas = ["public", "storage"]

[db]
port = 5432
shadow_port = 5431
major_version = 15

[realtime]
enabled = true

[studio]
enabled = true
port = 8082

[inbucket]
enabled = true
port = 8084

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"

[functions.openai-bot]
verify_jwt = true

[functions.whatsapp-integration]
verify_jwt = true

[functions.create-admin-user]
verify_jwt = false

